name: Build OVPN30

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenVPN XOR
        uses: actions/checkout@v4
        with:
          repository: lawtancool/ics-openvpn-xor
          ref: master
          submodules: true
          path: upstream

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Prepare Gradle
        run: |
          chmod +x upstream/gradlew
          mkdir -p ~/.gradle
          echo "icsopenvpnDebugSign=true" > ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx2048M" >> ~/.gradle/gradle.properties

      - name: Build OVPN30
        working-directory: upstream
        run: ./gradlew assembleUiOvpn2Release --stacktrace

      - name: Find APK
        run: |
          find upstream/main/build/outputs/apk -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OVPN30-APK
          path: upstream/main/build/outputs/apk/**/*universal*.apk
          if-no-files-found: error
